######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 8 16:41:49 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += testdb.cpp
